name: Deploy to AWS EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node_modules-

            - name: Install dependencies
              run: npm ci

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  envs: |
                      GIT_HUB_ACCESS_TOKEN=${{ secrets.GIT_HUB_ACCESS_TOKEN }}
                      RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
                  script: |
                      cd /home/ubuntu

                      if [ ! -d "NEW-PORTFOLIO" ]; then
                        git clone https://github.com/BabylooPro/NEW-PORTFOLIO.git
                      fi

                      cd NEW-PORTFOLIO

                      git pull origin main

                      npm ci --prefix .
                      npm run build --prefix .

                      if pm2 list | grep -q "portfolio"; then
                        pm2 restart portfolio --update-env
                      else
                        pm2 start npm --name "portfolio" -- start --prefix . --update-env
                      fi

                      pm2 save
