name: Deploy to AWS EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            GIT_HUB_ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
            RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node_modules-

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      cd /home/ubuntu

                      if [ ! -d "NEW-PORTFOLIO" ]; then
                        git clone https://github.com/BabylooPro/NEW-PORTFOLIO.git
                      fi

                      cd NEW-PORTFOLIO

                      git pull origin main

                      RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
                      GIT_HUB_ACCESS_TOKEN=${{ secrets.GIT_HUB_ACCESS_TOKEN }} \
                      WAKATIME_API_KEY=${{ secrets.WAKATIME_API_KEY }} \
                      NODE_OPTIONS="--max-old-space-size=3072" \
                      npm ci --prefix .

                      RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
                      GIT_HUB_ACCESS_TOKEN=${{ secrets.GIT_HUB_ACCESS_TOKEN }} \
                      WAKATIME_API_KEY=${{ secrets.WAKATIME_API_KEY }} \
                      NODE_OPTIONS="--max-old-space-size=3072" \
                      npm run build --prefix .

                      # INFO: THE COMMAND NPM TEST HAS BEEN DISABLED TO AVOID FAILURES DUE TO MEMORY LIMITATIONS ON T2.MICRO EC2 INSTANCE (1GB RAM + 4GB SWAP).
                      # WARN: COMPLEX JEST TESTS MAY CAUSE OUT-OF-MEMORY (OOM) ERRORS.
                      #! TO FIXED: AN INSTANCE WITH MORE RAM MAY BE NEEDED TO RE-ENABLE THE TESTS.

                      pm2 delete portfolio || true
                      RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
                      GIT_HUB_ACCESS_TOKEN=${{ secrets.GIT_HUB_ACCESS_TOKEN }} \
                      WAKATIME_API_KEY=${{ secrets.WAKATIME_API_KEY }} \
                      pm2 start npm --name "portfolio" -- start --prefix /home/ubuntu/NEW-PORTFOLIO --update-env

                      pm2 save
