name: Deploy Production Frontend AWS Amplify

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    env:
      AWS_AMPLIFY_APP_ID: ${{ secrets.AWS_AMPLIFY_APP_ID }}
      AWS_ACCESS_KEY_ID_AMPLIFY: ${{ secrets.AWS_ACCESS_KEY_ID_AMPLIFY }}
      AWS_SECRET_ACCESS_KEY_AMPLIFY: ${{ secrets.AWS_SECRET_ACCESS_KEY_AMPLIFY }}
      GIT_HUB_ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      COUNTRY_STATE_CITY_API_KEY: ${{ secrets.COUNTRY_STATE_CITY_API_KEY }}
      STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
      STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
      NEXT_PUBLIC_STRAPI_API_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_AMPLIFY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_AMPLIFY }}
          aws-region: us-east-1

      - name: Configure Amplify for Next.js
        run: |
          APP_ID=${{ secrets.AWS_AMPLIFY_APP_ID }}
          REGION="us-east-1"
          BRANCH="main"

          aws amplify update-app --app-id $APP_ID --platform WEB_COMPUTE --region $REGION

          aws amplify update-branch --app-id $APP_ID --branch-name $BRANCH --framework 'Next.js - SSR' --region $REGION

          echo "Configured Amplify app platform and framework for Next.js"

      - name: Install dependencies
        run: npm install --legacy-peer-deps --force

      - name: Build app
        run: npm run build

      - name: Update environment variables in Amplify
        run: |
          APP_ID=${{ secrets.AWS_AMPLIFY_APP_ID }}
          BRANCH="main"

          cat > env-vars.json << EOL
          {
            "environmentVariables": {
              "GIT_HUB_ACCESS_TOKEN": "${{ secrets.GIT_HUB_ACCESS_TOKEN }}",
              "RESEND_API_KEY": "${{ secrets.RESEND_API_KEY }}",
              "WAKATIME_API_KEY": "${{ secrets.WAKATIME_API_KEY }}",
              "COUNTRY_STATE_CITY_API_KEY": "${{ secrets.COUNTRY_STATE_CITY_API_KEY }}",
              "STRAPI_API_TOKEN": "${{ secrets.STRAPI_API_TOKEN }}",
              "STRAPI_API_URL": "${{ secrets.STRAPI_API_URL }}",
              "NEXT_PUBLIC_STRAPI_API_URL": "${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }}",
              "AMPLIFY_MONOREPO_APP_ROOT": "frontend"
            }
          }
          EOL

          aws amplify update-branch --app-id $APP_ID --branch-name $BRANCH --environment-variables "$(cat env-vars.json | jq -c .environmentVariables)"

          echo "Updated environment variables in Amplify"

      - name: Deploy to AWS Amplify
        run: |
          APP_ID=${{ secrets.AWS_AMPLIFY_APP_ID }}
          BRANCH="main"

          echo "Triggering Amplify deployment via start-job..."
          aws amplify start-job --app-id $APP_ID --branch-name $BRANCH --job-type RELEASE

          echo "Amplify build triggered. Check the AWS Amplify Console for build progress."
