# INFO: THIS WORKFLOW IS USED TO TEST LOCAL BUILD AND DEPLOY FRONTEND USING NEKTOS/ACT IN A DOCKER CONTAINER
# VERSION: ACT 0.2.67 | DOCKER 27.2.0, build 3ab4256
# RUN: act -j deploy --secret-file .secrets -W ./.github/workflows/deploy-frontend-local-act.yml --container-architecture linux/amd64

name: Deploy Frontend Locally with Act

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy (GitHub Actions local - nektos/act)"
                default: "local"
                required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: frontend/node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('frontend/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node_modules-

            - name: Install dependencies
              run: npm ci --legacy-peer-deps
              env:
                  GIT_HUB_ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  COUNTRY_STATE_CITY_API_KEY: ${{ secrets.COUNTRY_STATE_CITY_API_KEY }}
                  STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
                  STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
                  NEXT_PUBLIC_STRAPI_API_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }}

            - name: Run unit tests
              run: npm test
              env:
                  GIT_HUB_ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  COUNTRY_STATE_CITY_API_KEY: ${{ secrets.COUNTRY_STATE_CITY_API_KEY }}
                  TEST_ENV: jsdom

            - name: Run integration tests
              run: npm run test:integration
              env:
                  GIT_HUB_ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  COUNTRY_STATE_CITY_API_KEY: ${{ secrets.COUNTRY_STATE_CITY_API_KEY }}
                  TEST_TYPE: integration
                  TEST_ENV: node

            - name: Build project
              run: npm run build
              env:
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
                  GIT_HUB_ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  COUNTRY_STATE_CITY_API_KEY: ${{ secrets.COUNTRY_STATE_CITY_API_KEY }}
                  STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
                  STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
                  NEXT_PUBLIC_STRAPI_API_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }}

            - name: Install PM2
              run: npm install -g pm2

            - name: Start frontend locally
              run: |
                  pm2 describe frontend > /dev/null && pm2 restart frontend --update-env || pm2 start npm --name "frontend" -- start --update-env
                  pm2 save
              env:
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
                  GIT_HUB_ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  COUNTRY_STATE_CITY_API_KEY: ${{ secrets.COUNTRY_STATE_CITY_API_KEY }}
                  STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
                  STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
                  NEXT_PUBLIC_STRAPI_API_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }}
