name: Deploy to AWS EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      cd NEW-PORTFOLIO

                      git pull origin main

                      npm install
                      npm run build

                      echo "export GIT_HUB_ACCESS_TOKEN=${{ secrets.GIT_HUB_ACCESS_TOKEN }}" | sudo tee -a /etc/environment
                      source /etc/environment

                      if [ -z "$GIT_HUB_ACCESS_TOKEN" ]; then
                        echo "ENVIRONMENT VARIABLE GIT_HUB_ACCESS_TOKEN IS NOT DEFINED."
                        exit 1
                      else
                        echo "ENVIRONMENT VARIABLE GIT_HUB_ACCESS_TOKEN IS DEFINED."
                      fi

                      if pm2 list | grep -q "portfolio"; then
                        pm2 restart portfolio --update-env
                      else
                        pm2 start npm --name "portfolio" -- run start --update-env
                      fi

                      pm2 save
