name: Test SSH Connection to EC2

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test SSH Connection - CMS Instance
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.CMS_EC2_HOST }}
          username: ${{ secrets.CMS_EC2_USER }}
          key: ${{ secrets.CMS_EC2_KEY }}
          debug: false
          script: |
            uptime 2>/dev/null
            hostname 2>/dev/null

      - name: Test SSH Connection - Frontend Instance
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.FRONTEND_EC2_HOST }}
          username: ${{ secrets.FRONTEND_EC2_USER }}
          key: ${{ secrets.FRONTEND_EC2_KEY }}
          debug: false
          script: |
            OUTPUT=$(uptime 2>&1)
            echo "$OUTPUT"
            HOSTNAME=$(hostname 2>&1)
            echo "$HOSTNAME"
