name: Run Tests and Create Pull Request

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            GIT_HUB_ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
            RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node_modules-

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: |
                  npm test 2>&1 | tee test-output.log

            - name: Read and encode test output
              id: test_output
              run: echo "TEST_OUTPUT=$(base64 -w 0 test-output.log)" >> $GITHUB_ENV

            - name: Commit changes if any
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git add .
                  git diff --cached --exit-code || git commit -m "Apply changes after running tests"

            - name: Push changes to test-results/pr
              run: |
                  git push origin HEAD:test-results/pr

            - name: Create Pull Request with Test Results
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.GH_PAT }}
                  commit-message: "Test Results: Update"
                  branch: test-results/pr
                  title: "Test Results"
                  body: |
                      ## Test Output
                      ```bash
                      $(echo ${{ env.TEST_OUTPUT }} | base64 --decode)
                      ```
                      ## Files Changed
                      The following files were modified:
                      ```bash
                      $(git diff --name-only HEAD~1 HEAD)
                      ```
                  committer: GitHub <noreply@github.com>
                  author: BabylooPro <BabylooPro@users.noreply.github.com>
                  signoff: false
                  delete-branch: false
                  draft: false

            - name: Upload Test Results as Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: test-results
                  path: test-output.log
